### ISSUE TITLE
Server's down for maintenence

### ISSUE THREAD

**Issue by rderewianko** [raveious/slack-announcement-approval#3]
I'd love to deploy it myself but I don't have enough experience doing so.. :( The heroku server you have for it, has decided it's on Christmas break.

**Comment by raveious** [comment]
I posted this after you forked the repo, but I made a comment [here ](https://github.com/raveious/slack-announcement-approval#development-delays) about how I am currently going through finals week in graduate school. I put the server into a maintenance mode to make sure I don't continue working on it instead of studying for my exams. Sorry for the confusion, I'm going to go back to developing on this in a few days.

**Comment by rderewianko** [comment]
Ah! My apologies! Thanks for all you do and good luck in exams!

**Comment by raveious** [comment]
Alright. So now I can go back to actively working on this. I would hold off until this hits the app directory to add it to your Slack team. Hopefully its not too much of an inconvenience.

**Comment by rderewianko** [comment]
Nope! Good things are worth the wait. Thanks for all you do.
